import Head from "next/head";
import Home from "./otherStuff/home";


export default function All() {
  return (
    <div>
      <Head>
        <title>Elif Shafak</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />

    </div>
  );
}
  