import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Elif Shafak</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="title">
          welcome to Elif Shafak's Official Website <br />
        </h1>
        <div className={styles.coming}>
          <h2>Coming Soon</h2>
        </div>
        <div className={styles.newestOne}>
          <div className="row container d-flex align-items-center">
            <div className="col-md-3 text-center">
              <Image
                src="/newestBook.jpg"
                layout="responsive"
                height={320}
                width={215}
              />
            </div>
            <div className="col-md-9 mt-4">
              <p>
                <strong>Title :</strong> The Island of missing trees
              </p>
              <p>
                <strong>Author :</strong> Elif Shafak
              </p>
              <p>
                <strong>Releasing Date :</strong> 05 - 08 - 2021
              </p>
              <p className="text-justify">
                <strong>Description :</strong> Lorem ipsum dolor sit amet
                consectetur adipisicing elit. Dolores, suscipit architecto
                consectetur accusamus saepe assumenda, culpa, nisi quidem
                cupiditate quibusdam facere. Quasi et repellat excepturi
                voluptas, quas dolores error nobis blanditiis aliquam,
                inventore, reiciendis tempora beatae voluptate fugit cum dolore
                ipsa provident architecto illum a facere veritatis ut impedit.
                Perspiciatis, optio libero aperiam magni hic voluptate
                consequatur provident possimus nesciunt.
              </p>
              <p>
                <strong>Price :</strong> 20 £
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
